name: CI

on:
  push:
  schedule:
    - cron: 0 2 * * 1-7

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        XOS_REVISION="XOS-9.0"
        Device="cheeseburger"

        for command in git curl wget make python java type which [ [[; do
          hash $command || type $command
        done
        mkdir -p src bin
        export PATH="$(pwd)/bin:$PATH"
        if [ "$(python --version | cut -d \' \' -f2 | cut -d \'.\' -f1)" == "3" ]; then
          echo "Found Python 3, but need 2. Trying to find a solution..."
          if ! hash python2; then
            echo "Need Python 2"
            exit 1
          else
            echo "Symlinking python2 to bin/python"
            ln -sf $(which python2) bin/python
            python --version
          fi
        fi
        
        if ! [ -x bin/repo ]; then
          echo "Downloading repo..."
          curl https://storage.googleapis.com/git-repo-downloads/repo > bin/repo
          chmod a+x bin/repo
        fi

        cd src
        
        if [ ! -d .repo ]; then
          repo init -u https://git.halogenos.org/halogenOS/android_manifest.git -b "$XOS_REVISION"
        fi

        if [ -d build/make -a -d external/xos -a -d vendor/aosp ]; then
          echo "Bootstrap sync not necessary."
        else
          echo "Doing boostrap sync..."
          repo sync -c --no-tags --no-clone-bundle -f -j2 build/make external/xos vendor/aosp
        fi
        
        cd external/xos
        git fetch XOS
        git reset --hard XOS/${XOS_REVISION}
        cd ../..
        source build/envsetup.sh
        reporeset
        reposync
        
        if ! type breakfast 2>&1 >/dev/null; then
          source build/envsetup.sh
        fi
        set +e
        breakfast "$Device"
        set -e
        echo "Checking if everything is alright..."
        if ! find device -name "$Device" -type d -mindepth 2 -maxdepth 2; then
          exit 1
        fi
        
        hostname() {
          echo "halogenOS"
        }
        LC_ALL=C LOCALVERSION=-halogenOS build full aosp_$Device-userdebug
